<?php

/**
 * Implements hook_menu()
 */
function may_bragdon_menu() {
  $items = array();

  //allow mods metadata to be loaded for the specified islandora object
  $items['may_bragdon/mods/%islandora_object'] = array(
    'title' => 'Citation Block Callback',
    'access callback' => 'islandora_object_access_callback',
    'access arguments' => array(ISLANDORA_VIEW_OBJECTS, 2),
    'page callback' => 'may_bragdon_object_mods',
    'page arguments' => array(2),
    'file' => 'includes/callbacks.inc',
    'type' => MENU_NORMAL_ITEM,
  );
  return $items;
}

function may_bragdon_menu_alter(&$items){

    //$items["islandora/object/%islandora_object/tei_viewer/markup"]["page callback"] = "may_bragdon_viewer_get_markup";
    //dpm($items);
}

function may_bragdon_preprocess_islandora_paged_tei_seadragon_viewer(&$variables) {
  //dpm("whoo hoo2");
  /*
  module_load_include('inc', 'may_bragdon', 'includes/utilities');

  $mod_path = drupal_get_path('module', 'tei_viewer');
  drupal_add_js(
    array(
      'islandora_paged_tei_tei' => array(
        'populated_tei' => TRUE,
      ),
    ),
    'setting'
  );
  drupal_add_js("$mod_path/js/viewer.js");

  $variables['markup'] = may_bragdon_viewer_get_markup(islandora_object_load($variables['page_pid']));
  $variables['tei_viewer_links'] = array(
    '#type' => 'markup',
    'annotate' => array(
      '#theme' => 'html_tag',
      '#tag' => 'a',
      '#value' => t('Annotate'),
      '#attributes' => array(
        'id' => 'tei-viewer-annotate',
        'href' => '#',
        'title' => t('Annotate'),
      ),
    ),
    'occluded' => array(
      '#theme' => 'html_tag',
      '#tag' => 'a',
      '#value' => t('Occluded Version'),
      '#attributes' => array(
        'id' => 'tei-viewer-occluded',
        'href' => '#',
        'title' => t('View Occluded'),
      ),
    ),
  );
  if (isset($variables['button_label'])) {
    $variables['button_label'] = t('Toggle Text');
  }*/
}

/**
 * Javascript to be added for the may bragdon site.
 *
 * @param type $javascript
 */
function may_bragdon_js_alter(&$javascript){
    drupal_add_js(drupal_get_path('module', 'may_bragdon') . '/js/citation_compound_block.js');
}

/**
 * Implements hook_preprocess(). This allows the large image display for
 * includsions to be edited if needed.
 */
function may_bragdon_preprocess_islandora_large_image(&$variables) {

   module_load_include('inc', 'may_bragdon', 'theme/theme');
   module_load_include('inc', 'islandora', 'includes/utilities');
   $themed_siblings = array();
   $islandora_object = $variables['islandora_object'];

   $compound_info = islandora_compound_object_retrieve_compound_info($islandora_object);
   $parts = islandora_object_load($compound_info['parent_pid']);

   // Need at least title, full name of at least one author, publication year.
  if (!isset($parts['MODS']) || !islandora_datastream_access(ISLANDORA_VIEW_OBJECTS, $parts['MODS'])) {
    return FALSE;
  }
  else {
    $info = get_data($parts);

    $tags = array();
    $tags['citation_author'] = array();
    $mods = $parts['MODS']->content;
    $mods_xml = new SimpleXMLElement($mods);
    $mods_xml->registerXPathNamespace('mods', 'http://www.loc.gov/mods/v3');


    //$title_results = $mods_xml->xpath('//mods:mods[1]/mods:titleInfo/mods:title');
    //$title = (string) reset($title_results);
  }

}

/**
 * Method to get the mods data if needed
 *
 * @param type $object
 * @return type
 */
function get_data($object){

    if (!(isset($object['MODS']) && islandora_datastream_access(ISLANDORA_VIEW_OBJECTS, $object['MODS']))) {
    return array();
  }
    $fields = array(
    'Title' => '//mods:title',
    'Subtitle' => '//mods:subTitle',
    'Date' => '//mods:dateCreated | //mods:dateIssued',
    'Name' => array('//mods:name', 'mods:namePart'),
    'Abstract' => '//mods:abstract',
    'Identifier' => '//mods:identifier',
    'Physical Description' => array('//mods:physicalDescription', 'mods:extent | mods:form | mods:note[not(@*)] | mods:note[@type="physical"] | mods:note[@type="details"] | mods:scale | mods:coordinates'),
    'Page' => array('//mods:physicalDescription', 'mods:extent'),
    'Topic' => '/mods:mods/mods:subject/mods:topic',
    'Continent' => '//mods:continent',
    'Country' => '//mods:country',
    'Province' => '//mods:province',
    'County' => '//mods:county',
    'Region/Lot' => '//mods:region',
    'City' => '//mods:city',
    'City Section' => '//mods:citySection',
    'Access' => '//mods:accessCondition',
    'Use and Reproduction' => '//mods:accessCondition[@type="useAndReproduction"]',
    'Restrictions on Access' => '//mods:accessCondition[@type="restrictionOnAccess"]',
    'Physical Location' => '//mods:physicalLocation',
  );

  $xml = simplexml_load_string($object['MODS']->content);

  $import = importFromXMLString($object['MODS']->content,
          'http://www.loc.gov/mods/v3');



  $xml->registerXPathNamespace('mods', 'http://www.loc.gov/mods/v3');
  $to_string = function($o) {
    return (string) $o;
  };
  // Query each context node with the given xpath.
  $query_each_context = function (array $contexts, $xpath) {
    $query = function(&$context, $key, $xpath) {
      $context->registerXPathNamespace('mods', 'http://www.loc.gov/mods/v3');
      $context = $context->xpath($xpath);
    };
    // Map values to each context node.
    array_walk($contexts, $query, $xpath);
    // Flatten to an array of values.
    return count($contexts) ? call_user_func_array('array_merge', $contexts) : array();
  };
  // Query the given xpath. If the xpath is any array the first value is the
  // xpath for the context node(s) and the second the path to the value fields.
  $query = function(SimpleXMLElement $xml, $xpath) use(&$query_each_context) {
    return is_string($xpath) ? $xml->xpath($xpath) : $query_each_context($xml->xpath($xpath[0]), $xpath[1]);
  };
  foreach ($fields as $label => $xpath) {
    $results = $query($xml, $xpath);
    // Remove empty values.
    $fields[$label] = array_filter(array_map($to_string, $results));
  }
  // Remove empty fields.
  return array_filter($fields);
}

  /**
   * Creates a new instance of the class by parsing the specifed namespace
   *
   * @param string $xml data stream to load
   * @param namespace information e.g. http://www.loc.gov/mods/v3
   *
   * @return key/value pair of xml data or null if the data stream does not exist
   *
   */
 function importFromXMLString($xml, $namespace) {
    $dc_doc = new DomDocument();
    if (!empty($xml) && $dc_doc->loadXML($xml)) {
      $tags = $dc_doc->getElementsByTagNameNS($namespace, '*');
      $xml_data = array();
      foreach ($tags as $child) {
        $xml_data[$child->nodeName][] = $child->nodeValue;
      }
      return $xml_data;
    }
    return NULL;
  }

/**
 * modify the theme registry to use the rochester template
 */
function may_bragdon_theme_registry_alter(&$theme_registry) {

  $module_path = drupal_get_path('module', 'may_bragdon');
  if (isset($theme_registry['islandora_compound_prev_next'])) {

    $theme_registry['islandora_compound_prev_next']['theme path'] = $module_path . '/theme';
    $theme_registry['islandora_compound_prev_next']['template'] = $module_path . '/theme/may-bragdon-compound-prev-next';
    $theme_registry['islandora_compound_prev_next']['includes'][0] = $module_path . '/theme/theme.inc';
    $theme_registry['islandora_compound_prev_next']['preprocess functions'][1] = "may_bragdon_template_preprocess_islandora_compound_prev_next";
  }

    
  if (isset($theme_registry['islandora_large_image'])) {
    $theme_registry['islandora_large_image']['theme path'] = $module_path . '/theme';
    $theme_registry['islandora_large_image']['template'] = $module_path . '/theme/islandora-large-image';

  }
}

/**
 * Define the URL for the page created
 */

function may_bragdon_simple_search_menu() {
  $items = array();
  $items[may_bragdon_module/form] = array(
    'title' => 'May Bragdon Simple Search',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('may_bragdon_simple_search_form'),
    'access arguments' => array('access content'),
    'description' => 'Simple Search for May Bragdon',
    'type' => MENU_CALLBACK,
  );

  return $items;
}

/**
 * Form builder function.
 */

function may_bragdon_simple_search_form($form, &$form_state) {

  $form['search_term'] = array(
    '#type' => 'textfield',
    '#title' => t('Search'),
  );
  return $form;
}
